# fly.toml file generated for lhci on 2023-04-04T00:50:55+09:00

app = "lhci"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
